ruleset:
  
  welcome_me:
  
    name: Introduce me to VarCI when I open a pull request
    events: [ pull_request ]
    when:
      - action = "opened"
      - user.login = "marktopper"
    comment: |
      Hey @{{ user.login }}! Thanks for contributing to REPOSITORY_NAME.
      We will be looking through your pull request as soon as possible.
  
  broken_links:
  
    name: Check for broken links in files
    events: [ pull_request ]
    message: >
      @{{ user.login }}, one of the links in the diff did not return an HTTP
      status code of 200. Please check for broken links. The broken link we
      found is `{{ diff_links.broken.0 }}`.
    when:
      - action = "opened" or action = "reopened"
      - count(diff_links.broken) > 0

  short_description:
    name: Close issues with short descriptions
    events: [ issues, pull_request ]
    when:
      - length(body) < 50
      - action = "opened" or action = "reopened"
    close: true
    message: >
      @{{ user.login }}, the issue description is too short. Please reopen it
      once you have amended the description to contain more than the requirement
      of 50 characters.
