ruleset:
  
  welcome_me:
  
    name: Introduce me to VarCI when I open a pull request
    events: [ pull_request ]
    when:
      - action = "opened"
      - user.login = "marktopper"
    comment: |
      Welcome to VarCI @{{ user.login }}!
  
      Continue pushing changes to the config in this branch and I'll validate the changes.
  
      You can also test out new rules in your pull requests before merging them.
  
      For example, try triggering the second rule by mentioning me (@VarCI-bot) right now!
  
  broken_links:
  
    name: Check for broken links in files
    events: [ pull_request ]
    message: >
      @{{ user.login }}, one of the links in the diff did not return an HTTP
      status code of 200. Please check for broken links. The first broken link
      is: {{ diff_links.broken.0 }}
    when:
      - action = "opened" or action = "reopened"
      - count(diff_links.broken) > 0

  short_description:
    name: Close issues with short descriptions
    events: [ issues ]
    when:
      - length(body) < 50
      - action = "opened" or action = "reopened"
    close: true
    message: >
      @{{ user.login }}, the issue description is too short. Please reopen it
      once you have amended the description to contain more than the requirement
      of 50 characters.
